// apps/admin-web/src/pages/AuditPage.tsx
import { ReloadOutlined } from "@ant-design/icons";
import { ProCard } from "@ant-design/pro-components/es/card";
import { useQuery } from "@tanstack/react-query";
import {
  Button,
  Input,
  Select,
  Space,
  Table,
  Tag,
  type TableColumnsType,
} from "antd";
import { useMemo, useState } from "react";
import { adminApi } from "../api";
import { Page } from "../components/Page";
import {
  actionLabel,
  categoryLabel,
  formatDateTime,
} from "../format";
import type { AuditEvent } from "../types";

export function AuditPage() {
  const [category, setCategory] = useState<string>();
  const [search, setSearch] = useState("");
  const query = useQuery({
    queryKey: ["admin", "audit"],
    queryFn: adminApi.audit,
  });
  const events = useMemo(() => {
    const keyword = search.trim().toLocaleLowerCase();
    return (query.data?.events ?? []).filter(
      (event) =>
        (!category || event.category === category) &&
        (!keyword ||
          event.action.toLocaleLowerCase().includes(keyword) ||
          actionLabel(event.action).toLocaleLowerCase().includes(keyword) ||
          event.detail.toLocaleLowerCase().includes(keyword) ||
          event.target_id?.toLocaleLowerCase().includes(keyword)),
    );
  }, [category, query.data, search]);

  const columns: TableColumnsType<AuditEvent> = [
    {
      title: "序号",
      dataIndex: "sequence",
      width: 90,
    },
    {
      title: "时间",
      dataIndex: "occurred_at",
      width: 180,
      render: (value: string) => formatDateTime(value),
      defaultSortOrder: "descend",
      sorter: (left, right) => left.sequence - right.sequence,
    },
    {
      title: "类别",
      dataIndex: "category",
      width: 100,
      render: (value: string) => categoryLabel(value),
    },
    {
      title: "操作",
      dataIndex: "action",
      width: 160,
      render: (value: string) => actionLabel(value),
    },
    {
      title: "目标",
      dataIndex: "target_id",
      width: 220,
      ellipsis: true,
    },
    {
      title: "说明",
      dataIndex: "detail",
      ellipsis: true,
    },
    {
      title: "结果",
      dataIndex: "outcome",
      width: 90,
      render: (_, event) => (
        <Tag color={event.outcome === "success" ? "success" : "error"}>
          {event.outcome === "success" ? "成功" : "失败"}
        </Tag>
      ),
    },
  ];

  return (
    <Page title="审计日志" error={query.error}>
      <ProCard
        title={`审计记录（${events.length}）`}
        variant="outlined"
        extra={
          <Space wrap>
            <Select
              allowClear
              placeholder="全部类别"
              value={category}
              onChange={setCategory}
              options={[
                { value: "auth", label: "认证" },
                { value: "room", label: "房间" },
                { value: "matchmaking", label: "匹配" },
                { value: "game", label: "对局" },
                { value: "admin", label: "管理" },
              ]}
            />
            <Input.Search
              allowClear
              placeholder="搜索操作、说明或目标 ID"
              value={search}
              onChange={(event) => setSearch(event.target.value)}
            />
            <Button
              aria-label="刷新审计日志"
              icon={<ReloadOutlined />}
              onClick={() => query.refetch()}
            />
          </Space>
        }
      >
        <Table<AuditEvent>
          rowKey="sequence"
          loading={query.isLoading}
          dataSource={events}
          columns={columns}
          scroll={{ x: 1080 }}
          pagination={{ pageSize: 20, showSizeChanger: true }}
        />
      </ProCard>
    </Page>
  );
}

// apps/admin-web/src/pages/AuditPage.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import Button from "primevue/button";
import Column from "primevue/column";
import DataTable from "primevue/datatable";
import IconField from "primevue/iconfield";
import InputIcon from "primevue/inputicon";
import InputText from "primevue/inputtext";
import Select from "primevue/select";
import Tag from "primevue/tag";
import { adminApi } from "../api";
import PageShell from "../components/PageShell.vue";
import { useResource } from "../composables/useResource";
import { actionLabel, categoryLabel, formatDateTime } from "../format";

const resource = useResource(adminApi.audit);
const search = ref("");
const category = ref<string>();
const categories = [
  { label: "认证", value: "auth" }, { label: "房间", value: "room" },
  { label: "匹配", value: "matchmaking" }, { label: "对局", value: "game" },
  { label: "管理", value: "admin" },
];
const events = computed(() => {
  const keyword = search.value.trim().toLocaleLowerCase();
  return (resource.data.value?.events ?? []).filter((event) =>
    (!category.value || event.category === category.value) &&
    (!keyword || `${event.action} ${actionLabel(event.action)} ${event.detail} ${event.target_id ?? ""}`.toLocaleLowerCase().includes(keyword)),
  );
});
</script>

<template>
  <PageShell title="审计日志" :error="resource.error.value" :loading="resource.loading.value">
    <template #actions><Button icon="pi pi-refresh" severity="secondary" variant="outlined" aria-label="刷新" :loading="resource.loading.value" @click="resource.reload" /></template>
    <DataTable :value="events" data-key="sequence" paginator :rows="20" :rows-per-page-options="[10, 20, 50]" sort-field="sequence" :sort-order="-1" scrollable table-style="min-width: 68rem" current-page-report-template="共 {totalRecords} 项">
      <template #header>
        <div class="flex align-items-center justify-content-between gap-3 flex-wrap px-1">
          <span>审计记录（{{ events.length }}）</span>
          <div class="flex gap-2 flex-wrap">
            <Select v-model="category" :options="categories" option-label="label" option-value="value" show-clear placeholder="全部类别" />
            <IconField><InputIcon class="pi pi-search" /><InputText v-model="search" placeholder="搜索操作、说明或目标 ID" /></IconField>
          </div>
        </div>
      </template>
      <Column field="sequence" header="序号" sortable style="width: 6rem" />
      <Column field="occurred_at" header="时间" style="width: 12rem"><template #body="{ data }">{{ formatDateTime(data.occurred_at) }}</template></Column>
      <Column field="category" header="类别" style="width: 7rem"><template #body="{ data }">{{ categoryLabel(data.category) }}</template></Column>
      <Column field="action" header="操作" style="width: 11rem"><template #body="{ data }">{{ actionLabel(data.action) }}</template></Column>
      <Column field="target_id" header="目标" style="width: 15rem" />
      <Column field="detail" header="说明" />
      <Column field="outcome" header="结果" style="width: 6rem"><template #body="{ data }"><Tag :severity="data.outcome === 'success' ? 'success' : 'danger'" :value="data.outcome === 'success' ? '成功' : '失败'" /></template></Column>
      <template #empty>暂无审计记录</template>
    </DataTable>
  </PageShell>
</template>
